# Generated by Django 3.0.5 on 2020-12-31 11:13

import BackEndApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('CNIC', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('address', models.CharField(max_length=999, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=BackEndApp.models.patient_profile)),
                ('verification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=999)),
                ('license_No', models.CharField(max_length=10)),
                ('branch_code', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=BackEndApp.models.laboratory_profile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('CNIC', models.CharField(max_length=13)),
                ('fName', models.CharField(max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('license_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('address', models.CharField(max_length=999, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=BackEndApp.models.doctor_profile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustedContact', to='BackEndApp.Patient')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_himself', to='BackEndApp.Patient')),
            ],
        ),
    ]
