# Generated by Django 3.0.5 on 2020-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
