# Generated by Django 3.0.5 on 2021-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='doctor',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
