# Generated by Django 3.0.5 on 2021-07-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
