# Generated by Django 3.0.5 on 2021-01-07 08:23

import BackEndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='label',
            field=models.CharField(default='Testing Upload', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=BackEndApp.models.patient_profile),
        ),
    ]
