# Generated by Django 3.0.5 on 2021-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='criticalLevel',
            field=models.TextField(default='normal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='criticalLevel',
            field=models.TextField(default='normal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionfiles',
            name='date',
            field=models.DateField(default='2021-07-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionfiles',
            name='description',
            field=models.CharField(default='null', max_length=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionfiles',
            name='label',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportfiles',
            name='date',
            field=models.DateField(default='2021-07-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportfiles',
            name='description',
            field=models.CharField(default='null', max_length=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportfiles',
            name='label',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
