# Generated by Django 3.0.5 on 2021-01-03 11:23

import BackEndApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=BackEndApp.models.prescriptions)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=99999)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BackEndApp.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEndApp.Patient')),
            ],
        ),
    ]
