# Generated by Django 3.0.5 on 2020-12-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'default_permissions': ('add',), 'permissions': (('add_report', 'Add Test Report'), ('add_prescription', 'Add Doctor Prescription'))},
        ),
    ]
