# Generated by Django 3.0.5 on 2020-12-30 16:54

import BackEndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=BackEndApp.models.doctor_profile),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=BackEndApp.models.patient_profile),
        ),
    ]
