# Generated by Django 3.0.5 on 2021-07-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='license_No',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
