# Generated by Django 3.0.5 on 2021-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0002_auto_20210716_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.TextField(default='Lahore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='city',
            field=models.TextField(default='Lahore'),
            preserve_default=False,
        ),
    ]
