# Generated by Django 3.0.5 on 2021-05-06 14:59

import BackEndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0002_labreport_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=BackEndApp.models.doctor_profile),
        ),
    ]
