# Generated by Django 3.0.5 on 2021-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0002_auto_20210723_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='city',
            field=models.CharField(default='Lahore', max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='city',
            field=models.CharField(default='Lahore', max_length=99),
            preserve_default=False,
        ),
    ]
