# Generated by Django 3.0.5 on 2021-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0003_auto_20210506_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='trustedContact',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
