# Generated by Django 3.0.5 on 2021-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0004_auto_20210701_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
