# Generated by Django 3.0.5 on 2021-07-06 07:46

import BackEndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0005_auto_20210704_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=BackEndApp.models.patient_profile),
        ),
    ]
