# Generated by Django 3.0.5 on 2021-07-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0006_auto_20210706_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='file',
        ),
    ]
