# Generated by Django 3.0.5 on 2021-07-06 10:25

import BackEndApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEndApp', '0007_remove_prescription_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescriptionFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField()),
                ('file', models.FileField(upload_to=BackEndApp.models.prescriptions)),
            ],
        ),
    ]
